---
title: "looping through"
output: html_document
---

```{r}
#load librarires, pacman pload installs missing libraries too
pacman::p_load(jsonlite,dplyr)


########################## Defining the function to return a dataframe with relevant tweets from all json nested lists
json_to_data<-function(json_file){
  #making sure the variable df is empty
  df<-NULL
  #create a dataframe with columns for Date, ID, text of the tweet, and language in right format
  df <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
  #name columns
  colnames(df)<-c("Datetime","ID","Text","Language")
  
  #read the json file into R: every tweet has its own list of lists with the text being hidden somewhere inside
  jsond<-lapply(readLines(json_file), fromJSON)
  
  #loop for looking through every list (tweet) in jsond
  for (tweet in jsond){
  x=length(tweet) #need to see how big the list is, if it is less than two, it is empty
  if(x < 2){ 
    next #skip empty lists
    } else {
      y<-tweet$lang #to save resources for filtering, better make sure the tweet is in english first
      if(y=="en"){
        userinfo<-tweet$user #userinfo needed to account for repeated measures (multiple tweets per user)for the validity of stats
        
        #some tweets have 'extended tweet' list and then the full text is in there
        #some tweets have only short/incomplete versions of the full text, take it if we are desperate (the else condition)
        if(('extended_tweet' %in% tweet)){
          tweettextlist<-tweet$extended_tweet
          #extract the fll text
          tweettext<-tweettextlist$full_text
        } else{ 
          tweettext<-tweet$text
        }
        #make a temporary list with extrected time, user name, text of the tweet (full or incomplete), and language
          temporary<-c(tweet$created_at,userinfo$screen_name,tweettext, tweet$lang)
          #make a matrix out of the list so it can be easily appended to the big dataframe
          temporary2<-as.matrix(temporary)
          #transpose the given matrix for better merging
          temp3<-t(temporary2)
          #make it as a data frame with the column names matching the main dataframe 'df'
          tempdata<-as.data.frame(temp3)
          colnames(tempdata)<-c("Datetime","ID","Text","Language")
          
          #bind the separate tweet with the main data frame
          df<-rbind(df,tempdata)
          colnames(df)<-c("Datetime","ID","Text","Language") #resetting names
        
      } else{
        next} #skip non-english tweets
      }
}
  #filter the entire dataframe for containment of any of the strings listed in the parantheses 
  gundata<-dplyr::filter(df, grepl('firearm|#gun|#guns|#gundebate|gun debate|second amendment|#2A|2ndamendment|2nd amendment|gunsensepatriot|momsdemand|nowaynra|gunskill|gunviolence|gun violence|guncontrol|gun control|gunsense|gun sense|gun ban|gunsafety|gun safety|gunrights|gun rights|protect2a|progun|nogunregistry|gungrab|gunfriendly|#NRA|2AShallNotBeInfringed|#shooting|mass shooting', Text))
  
  #the output of the function: gun related tweets with datetime, id, text, and language
  return(gundata)
}
```


Learning how to do a loop through a day. It is commented out since it takes a long time to run
```{r}
# #set wd
# setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02")
# 
# bigdata<-NULL
# bigdata <- data.frame(Date=as.Date(character()),
#                  ID=character(),
#                  Text=character(),
#                  Language=character())
# colnames(bigdata)<-c("Datetime","ID","Text","Language")
# 
# #Make a loop through just one day
# days<-list.dirs(recursive = F)
# day1<-days[1]
# hours1<-list.dirs(day1)
# 
# jsonfile<-("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/01/23/50.json.bz2")
# jsond<-lapply(readLines(jsonfile), fromJSON)
# tryhard<-json_to_data(jsonfile)
# 
# #############set wd to ./01
# setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/01")
# hours1<-list.dirs(recursive = F)
# 
# #imitating big data
# notbigdata<-NULL
# notbigdata <- data.frame(Date=as.Date(character()),
#                  ID=character(),
#                  Text=character(),
#                  Language=character())
# colnames(notbigdata)<-c("Datetime","ID","Text","Language")
# 
# 
# for(hour in hours1){
#   file.names <- dir(hour, pattern =".json")
#   for(f in file.names){
#     daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/01")
#     #x <- "R Tutorial"
#     #gsub("ut","ot",x)
#     #paste("file", "number", "32", sep = "_")
#     #[1] "file_number_32"
#     pathtofile=paste(daypath,hour,f,sep = "/")
#     #print(pathtofile) #works
#     tryh<-json_to_data(pathtofile)
#     notbigdata<-rbind(notbigdata,tryh)
#   }
# }

```


That worked, make a loop that'd go through all days in February

```{r}
# #set wd
# setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02")
# 
# bigdata<-NULL
# bigdata <- data.frame(Date=as.Date(character()),
#                  ID=character(),
#                  Text=character(),
#                  Language=character())
# colnames(bigdata)<-c("Datetime","ID","Text","Language")
# 
# days<-list.dirs(recursive = FALSE)
# 
# for (day in days) { #access a day in february
#   
#   wd=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02")
#   #day=gsub("./", "", c)
#   newpath=paste(wd,day,sep = "/")
#   # do stuff
#   #hourlist[1]<-("00")
#   for (hour in hourlist){ #access an hour in a day
#     # newpath2<-paste(newpath,hour,sep = "/")
#     for(f in file.names){
#       extranewpath<-paste(newpath,hour,f,sep = "/")
#       tinydata<-json_to_data(f)
#       bigdata<-rbind(bigdata,tinydata)
#     }
#   }
# }

```

I give up on the loooooop, tired of stupid errors, so I am doing it manually, as I really need to move on!!!

It's stupid, but it works! Doing the same thing 28 times manually is not that bad..

```{r}
#load libraries
pacman::p_load(jsonlite,dplyr)

#all bits here start with setting the working directory to the day we want to filter

#############set wd to ./01
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/01")
#list the files in the directory: evey directory (day) has multiple folders (hours)
hours1<-list.dirs(recursive = F)

#reset the bigdata variable
bigdata<-NULL

#create new bigdata data frame with correct column names
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

#go through the list of files (in this case folders) in the directory
for(hour in hours1){
  #list all files in the current folder that are of json format
  file.names <- dir(hour, pattern =".json")
  #go through every json file in the list of json files
  for(f in file.names){
    #define the string for the name of the directory, so we can automatize finding the path to the particular file
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/01")
    
    #####Example of smth we want to do, but instead of writing parts manually we want to keep track of where in the loop we are
    #paste("file", "number", "32", sep = "_")
    #[1] "file_number_32"
    
    #Construct the string for the path that automatically takes wd,hour, and file based on where we are in the loop
    pathtofile=paste(daypath,hour,f,sep = "/")
    #print(pathtofile) #test if it works.. it does! Resulting string can actually be used as the path
    
    #apply our json_to_data function to the file specified in the path..
    tryh1<-json_to_data(pathtofile)
    
    #bind the data from the tweet with the full bigdata dataset
    bigdata<-rbind(bigdata,tryh1)
  }
}

#create a csv file for the first directory (day..) 27 more to go
write.csv(bigdata, file = "bigdata1n.csv")

#############Repeate for every day
#############set wd to ./02
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/02")
hours1<-list.dirs(recursive = F)

bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/02")
    #x <- "R Tutorial"
    #gsub("ut","ot",x)
    #paste("file", "number", "32", sep = "_")
    #[1] "file_number_32"
    pathtofile=paste(daypath,hour,f,sep = "/")
    #print(pathtofile) #works
    tryh2<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh2)
  }
}

write.csv(bigdata, file = "bigdata2n.csv")

#############set wd to ./03
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/03")
hours1<-list.dirs(recursive = F)

bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")


for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/03")
    #x <- "R Tutorial"
    #gsub("ut","ot",x)
    #paste("file", "number", "32", sep = "_")
    #[1] "file_number_32"
    pathtofile=paste(daypath,hour,f,sep = "/")
    #print(pathtofile) #works
    tryh3<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh3)
  }
}
write.csv(bigdata, file = "bigdata3n.csv")

#############set wd to ./04
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/04")
hours1<-list.dirs(recursive = F)

bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")


for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/04")
    #x <- "R Tutorial"
    #gsub("ut","ot",x)
    #paste("file", "number", "32", sep = "_")
    #[1] "file_number_32"
    pathtofile=paste(daypath,hour,f,sep = "/")
    #print(pathtofile) #works
    tryh4<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh4)
  }
}
write.csv(bigdata, file = "bigdata4n.csv")

#############set wd to ./05
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/05")
hours1<-list.dirs(recursive = F)

bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")


for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/05")
    #x <- "R Tutorial"
    #gsub("ut","ot",x)
    #paste("file", "number", "32", sep = "_")
    #[1] "file_number_32"
    pathtofile=paste(daypath,hour,f,sep = "/")
    #print(pathtofile) #works
    tryh5<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh5)
  }
}

write.csv(bigdata, file = "bigdata5n.csv")

#############set wd to ./06
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/06")
hours1<-list.dirs(recursive = F)

bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")


for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/06")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh6<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh6)
  }
}

write.csv(bigdata, file = "bigdata6n.csv")

#############set wd to ./07
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/07")
hours1<-list.dirs(recursive = F)

bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/07")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh7<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh7)
  }
}

write.csv(bigdata, file = "bigdata7n.csv")

#############set wd to ./08
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/08")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")


for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/08")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh8<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh8)
  }
}
write.csv(bigdata, file = "bigdata8n.csv")

#############set wd to ./09
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/09")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/09")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh9<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh9)
  }
}
write.csv(bigdata, file = "bigdata9n.csv")

#############set wd to ./10
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/10")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/10")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh10<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh10)
  }
}

write.csv(bigdata, file = "bigdata10n.csv")

#############set wd to ./11
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/11")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/11")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh11<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh11)
  }
}
write.csv(bigdata, file = "bigdata11n.csv")

#############set wd to ./12
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/12")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")


for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/12")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh12<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh12)
  }
}
write.csv(bigdata, file = "bigdata12n.csv")

#############set wd to ./13
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/13")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/13")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh13<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh13)
  }
}

write.csv(bigdata, file = "bigdata13n.csv")

#############set wd to ./14
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/14")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/14")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh14<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh14)
  }
}
write.csv(bigdata, file = "bigdata14.csv")

#############set wd to ./15
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/15")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/15")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh15<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh15)
  }
}

write.csv(bigdata, file = "bigdata15.csv")

#############set wd to ./16
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/16")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")


for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/16")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh16<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh16)
  }
}
write.csv(bigdata, file = "bigdata16.csv")

#############set wd to ./17
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/17")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/17")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh17<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh17)
  }
}
write.csv(bigdata, file = "bigdata17.csv")

#############set wd to ./18
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/18")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")


for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/18")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh18<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh18)
  }
}
write.csv(bigdata, file = "bigdata18.csv")

#############set wd to ./19
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/19")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/19")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh18<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh18)
  }
}
write.csv(bigdata, file = "bigdata19.csv")

#############set wd to ./20
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/20")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/20")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh18<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh18)
  }
}
write.csv(bigdata, file = "bigdata20.csv")

#############set wd to ./21
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/21")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")


for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/21")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh18<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh18)
  }
}
write.csv(bigdata, file = "bigdata21.csv")

#############set wd to ./22
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/22")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")


for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/22")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh18<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh18)
  }
}
write.csv(bigdata, file = "bigdata22.csv")

#############set wd to ./23
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/23")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")


for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/23")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh18<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh18)
  }
}
write.csv(bigdata, file = "bigdata23.csv")

#############set wd to ./24
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/24")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/24")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh18<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh18)
  }
}
write.csv(bigdata, file = "bigdata24.csv")

#############set wd to ./25
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/25")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")


for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/25")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh18<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh18)
  }
}
write.csv(bigdata, file = "bigdata25.csv")

#############set wd to ./26
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/26")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/26")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh18<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh18)
  }
}
write.csv(bigdata, file = "bigdata26.csv")

#############set wd to ./27
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/27")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/27")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh18<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh18)
  }
}
write.csv(bigdata, file = "bigdata27.csv")

#############set wd to ./28
setwd("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/28")
hours1<-list.dirs(recursive = F)
bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")

for(hour in hours1){
  file.names <- dir(hour, pattern =".json")
  for(f in file.names){
    daypath=("E:/Anita dat/archiveteam-twitter-stream-2018-02/2018/02/28")
    pathtofile=paste(daypath,hour,f,sep = "/")
    tryh18<-json_to_data(pathtofile)
    bigdata<-rbind(bigdata,tryh18)
  }
}
write.csv(bigdata, file = "bigdata28.csv")
```

