---
title: "Learning to filter tweets"
author: "Anita Kurm"
date: "November 19, 2018"
output: html_document
---

```{r}
##########################Defining the function

json_to_data<-function(json_file){
  df<-NULL
  df <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
  colnames(df)<-c("Datetime","ID","Text","Language")
  jsond<-lapply(readLines(json_file), fromJSON)
  for (tweet in jsond){
  x=length(tweet)
  if(x < 2){
    next
    } else {
      y<-tweet$lang
      if(y=="en"){
        userinfo<-tweet$user
        if(('extended_tweet' %in% tweet)){
          tweettextlist<-tweet$extended_tweet
          tweettext<-tweettextlist$full_text
        } else{
          tweettext<-tweet$text
        }
          temporary<-c(tweet$created_at,userinfo$screen_name,tweettext, tweet$lang)
          temporary2<-as.matrix(temporary)
          temp3<-t(temporary2)
          tempdata<-as.data.frame(temp3)
          colnames(tempdata)<-c("Datetime","ID","Text","Language")
          df<-rbind(df,tempdata)
          colnames(df)<-c("Datetime","ID","Text","Language") #resetting names
        
      } else{
        next}
      }
}
  
  gundata<-dplyr::filter(df, grepl('gun|guns|gundebate|2A|2ndamendment|guncontrol|gunsense|gunban|gunsafety|gunrights|NRA|2AShallNotBeInfringed|shooting', Text))
  return(gundata)
}
```

Make a loop to go through the folder

```{r}
path = "~/14"
file.names <- dir(path, pattern =".json")
for(i in 1:length(file.names)){
  json_to_data(i)
}

bigdata<-NULL
bigdata <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character(),
                 Language=character())
colnames(bigdata)<-c("Datetime","ID","Text","Language")


for (day in list.dirs(recursive=FALSE)) { #access a day in february
   ## do stuff
  for (hour in list.dirs(recursive = FALSE)){ #access an hour in a day
    file.names <- dir(hour, pattern =".json")
    for(i in 1:length(file.names)){
      tinydata<-json_to_data(i)
      bigdata<-rbind(bigdata,tinydata)
    # for (jsonfile in hour) { #access a file in an hour, shouldn't be compressed
    #   tinydata<-json_to_data(jsonfile)
    #   bigdata<-rbind(bigdata,tinydata)
    }
  }
}

```


