---
title: "Mass shootings"
author: "Anita Kurm"
date: "October 20, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#libraries
pacman::p_load(ggplot2,e1071,caret,quanteda,irlba, randomForest, doSNOW,lubridate)
pacman::p_load(scales)

#set wd
setwd("C:/Users/JARVIS/Desktop/Uni/Thesis/data scraping/BachelorProject")
```

Mass shootings 2018 dataframe
```{r}
#messy data
ds<- read.csv("massshootings2018.csv", header = T, stringsAsFactors = F)

#remove operation column
ds <- ds[, 1:6]

#make sure dates are seen as dates
ds$Incident.Date<-as_date(ds$Incident.Date, origin = lubridate::origin)

as.Date(ds$Incident.Date,format="%B %d, %Y")

ds$Incident.Date<- as_datetime(ds$Incident.Date)

#remove stuff before 2018?
ds2 <- ds[format(ds$Incident.Date,'%Y') != "2017", ]

#add a column for total victims (killed plus injured)
ds2$Total <- ds2$X..Killed+ds2$X..Injured

ds2$Incident.Date<- as_date(ds2$Incident.Date, origin = lubridate::origin)

```

Some easy plots
```{r}
#timeline of shootings x=time, y=number of killings
kills_plot<-ggplot(ds2, aes(x = ds2$Incident.Date , y=ds2$X..Killed)) +
  geom_smooth() +
  geom_point()+
  labs(y = "Killed", x = "time",
       title = "Timeline: number of killed")
kills_plot

#timeline of shootings x=time, y=number of injured
injured_plot<-ggplot(ds2, aes(x = ds2$Incident.Date , y=ds2$X..Injured)) +
  theme_minimal() +
  geom_smooth() +
  geom_point()+
  labs(y = "Injured", x = "time",
       title = "Timeline: number of injured")
injured_plot

#timeline of shootings x=time, y=total no of killed+injured
total_plot<-ggplot(ds2, aes(x = ds2$Incident.Date , y=ds2$Total)) +
  theme_bw() +
  geom_count()+
  labs(y = "Injured+Killed", x = "time",
       title = "Timeline: number of victims")
total_plot


number_ticks <- function(n) {function(limits) pretty(limits, n)}

#timeline of shootings x= continuous time, y=incitdent, size = number of total victim 
timeplot <-ggplot(ds2,aes(x=ds2$Incident.Date, y=Total, color=Total, size=Total) ) +
  theme_minimal()+
  geom_point()+
  geom_text(data=month_df, aes(x=month_date_range,y=-0.5,label=month_format),size=2.5,vjust=0.5, color='black', angle=90)+
  scale_x_datetime(breaks = scales::date_breaks("1 month"))+
  theme(axis.text.x =element_blank(),
                 axis.ticks.x =element_blank()
                )+
  labs(y = "Number of Injured+Killed victims", x = "time",
       title = "Number of victims plotted against timeline of corresponding incidents")
timeplot

```

Timeline recipe from the web:
```{r}
#Milestones = Address, Status=Total, 

positions <- c(0.5, -0.5, 1.0, -1.0, 1.5, -1.5)
directions <- c(1, -1)

line_pos <- data.frame(
    "Incident.Date"=unique(ds2$Incident.Date),
    "position"=rep(positions, length.out=length(unique(ds2$Incident.Date))),
    "direction"=rep(directions, length.out=length(unique(ds2$Incident.Date)))
)

ds2 <- merge(x=ds2, y=line_pos, by="Incident.Date", all = TRUE)

text_offset <- 0.05
ds2$month_count <- ave(ds2$Incident.Date ==ds2$Incident.Date, ds2$Incident.Date, FUN=cumsum)
ds2$text_position <- (ds2$month_count * text_offset * ds2$direction) + ds2$position

month_buffer <- 2

month_date_range <- seq(min(ds2$Incident.Date), max(ds2$Incident.Date), by='month')
month_format <- format(month_date_range, '%b')
month_df <- data.frame(month_date_range, month_format)

#### PLOT ####
timeline_plot<-ggplot(ds2,aes(x=Incident.Date,y=0, col=Total, label=ds2$Address))+
  labs(col="Number of victims")+
  scale_fill_distiller(palette = "Blues")+
  theme_classic()+
  geom_hline(yintercept=0, # Plot horizontal black line for timeline
                color = "black", size=0.3)+
  geom_point(aes(y=0), size=ds2$Total)+
  theme(axis.line.y=element_blank(),
                 axis.text.y=element_blank(),
                 axis.title.x=element_blank(),
                 axis.title.y=element_blank(),
                 axis.ticks.y=element_blank(),
                 axis.text.x =element_blank(),
                 axis.ticks.x =element_blank(),
                 axis.line.x =element_blank(),
                 legend.position = "bottom"
                )+
  geom_text(data=month_df, aes(x=month_date_range,y=-0.1,label=month_format),size=2.5,vjust=0.5, color='black', angle=90)
  #geom_text(aes(y=text_position,label=ds2$Address),size=2.5)
  



# Plot vertical segment lines for milestones
timeline_plot
```

