---
title: "Sentiment analysis"
author: "Anita Kurm"
date: "October 21, 2018"
output: html_document
---

Developing the data loading and processing pipeline
```{r}
# #####Try to extract a tweet
# #Step 1: extract a single tweet whole data
# data2<- data[[1]]
# #Step 2: extract everything but the 'state' list
# data3<- data2$dictitems
# #Step 3: extract datetime (created_at) and text (text)
# data4<-c(data3$created_at,data3$id_str,data3$retweeted,data3$text)
# #Cosmetic
# data5<-as.matrix(data4)
# data5<-t(data5)
# data6<-as.data.frame(data5)
# colnames(data6)<-c("Datetime","ID","Retweet","Text")
# 
# #success!
# d<-data6
# data2<-NULL
# data3<-NULL
# data4<-NULL
# data5<-NULL
# data6<-NULL
# 
# #trying empty dataframe
# df<-NULL
# df <- data.frame(Date=as.Date(character()),
#                  ID=character(), 
#                  Retweet=character(),
#                  Text=character())
# 
# colnames(df)<-c("Datetime","ID","Retweet","Text")
# 
# 
# #let's make a loop that will append info from each tweet to the dataframe
# for (tweetdata in data){                        #'tweetdata' contains all info on a single tweet
#   temporary<-tweetdata$dictitems                #'temporary' contains all info except the state list
#   temporary2<-c(temporary$created_at,temporary$id_str,temporary$retweeted,temporary$text)
#   temporary3<-as.matrix(temporary2)
#   temp4<-t(temporary3)
#   tempdata<-as.data.frame(temp4)
#   colnames(tempdata)<-c("Datetime","ID","Retweet","Text")
#   df<-rbind(df,tempdata)
#   colnames(df)<-c("Datetime","ID","Retweet","Text") #resetting names
# #   print(df)
# }
# #https://stackoverflow.com/questions/26508519/how-to-add-elements-to-a-list-in-r-loop
# 
# df<-rbind(df,temporary2)
# 
# datalist = list()
# 
# for (i in 1:5) {
#     # ... make some data
#     dat <- data.frame(x = rnorm(10), y = runif(10))
#     dat$i <- i  # maybe you want to keep track of which iteration produced it?
#     datalist[[i]] <- dat # add it to your list
# }
```



```{r setup, include=FALSE}
library(yaml)
pacman::p_load(dplyr)

#set wd
setwd("C:/Users/JARVIS/Desktop/Uni/Thesis/data scraping/BachelorProject")

#load data1. #Guncontrol 15-02-18 19:21
data<-yaml.load_file("data/guncontrol_150218_1920.yaml")

#creating empty dataframe
df<-NULL
df <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character())

colnames(df)<-c("Datetime","ID","Text")


#let's make a loop that will append info from each tweet to the dataframe
for (tweetdata in data){                        #'tweetdata' contains all info on a single tweet
  temporary<-tweetdata$dictitems                #'temporary' contains all info except the state list
  temporary2<-c(temporary$created_at,temporary$id_str,temporary$text)
  temporary3<-as.matrix(temporary2)
  temp4<-t(temporary3)
  tempdata<-as.data.frame(temp4)
  colnames(tempdata)<-c("Datetime","ID","Text")
  df<-rbind(df,tempdata)
  colnames(df)<-c("Datetime","ID","Text") #resetting names
#   print(df)
}

#add the column with the hashtag
df$hashtag<-rep("guncontrol",length(df$Text))

# Write CSV in R
write.csv(df, file = "data/guncontrol_150218_1920.csv",row.names=FALSE)

```

I know it is stupid, but i'll just manually sort the data out
Data: guncontrol 1 h before the shooting

```{r}
#load data2. #Guncontrol 1 h before the shooting
data<-yaml.load_file("data/guncontrol1_before.yaml")

#creating empty dataframe
df<-NULL
df <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character())

colnames(df)<-c("Datetime","ID","Text")


#let's make a loop that will append info from each tweet to the dataframe
for (tweetdata in data){                        #'tweetdata' contains all info on a single tweet
  temporary<-tweetdata$dictitems                #'temporary' contains all info except the state list
  temporary2<-c(temporary$created_at,temporary$id_str,temporary$text)
  temporary3<-as.matrix(temporary2)
  temp4<-t(temporary3)
  tempdata<-as.data.frame(temp4)
  colnames(tempdata)<-c("Datetime","ID","Text")
  df<-rbind(df,tempdata)
  colnames(df)<-c("Datetime","ID","Text") #resetting names
#   print(df)
}

#add the column with the hashtag
df$hashtag<-rep("guncontrol",length(df$Text))

# Write CSV in R
write.csv(df, file = "data/guncontrol_1402018_1920.csv",row.names=FALSE)

```

Data: gunrights 1h before
```{r}
#load data2. #Gunrights 1 h before the shooting
data<-yaml.load_file("data/gunrights_1h_before.yaml")

#creating empty dataframe
df<-NULL
df <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character())

colnames(df)<-c("Datetime","ID","Text")


#let's make a loop that will append info from each tweet to the dataframe
for (tweetdata in data){                        #'tweetdata' contains all info on a single tweet
  temporary<-tweetdata$dictitems                #'temporary' contains all info except the state list
  temporary2<-c(temporary$created_at,temporary$id_str,temporary$text)
  temporary3<-as.matrix(temporary2)
  temp4<-t(temporary3)
  tempdata<-as.data.frame(temp4)
  colnames(tempdata)<-c("Datetime","ID","Text")
  df<-rbind(df,tempdata)
  colnames(df)<-c("Datetime","ID","Text") #resetting names
#   print(df)
}

#add the column with the hashtag
df$hashtag<-rep("gunrights",length(df$Text))

# Write CSV in R
write.csv(df, file = "data/gunrights_1402018_1920.csv",row.names=FALSE)
```

Another one

```{r}
#load data2. #Guncontrol right after the shooting
data<-yaml.load_file("data/guncontrol_after2.yaml")

#creating empty dataframe
df<-NULL
df <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character())

colnames(df)<-c("Datetime","ID","Text")


#let's make a loop that will append info from each tweet to the dataframe
for (tweetdata in data){                        #'tweetdata' contains all info on a single tweet
  temporary<-tweetdata$dictitems                #'temporary' contains all info except the state list
  temporary2<-c(temporary$created_at,temporary$id_str,temporary$text)
  temporary3<-as.matrix(temporary2)
  temp4<-t(temporary3)
  tempdata<-as.data.frame(temp4)
  colnames(tempdata)<-c("Datetime","ID","Text")
  df<-rbind(df,tempdata)
  colnames(df)<-c("Datetime","ID","Text") #resetting names
#   print(df)
}

#add the column with the hashtag
df$hashtag<-rep("guncontrol",length(df$Text))

# Write CSV in R
write.csv(df, file = "data/gucontrol_1502018_0120.csv",row.names=FALSE)
```

And again
```{r}
#load data2. #Gunrights right after the shooting
data<-yaml.load_file("data/gunrights_after.yaml")

#creating empty dataframe
df<-NULL
df <- data.frame(Date=as.Date(character()),
                 ID=character(),
                 Text=character())

colnames(df)<-c("Datetime","ID","Text")


#let's make a loop that will append info from each tweet to the dataframe
for (tweetdata in data){                        #'tweetdata' contains all info on a single tweet
  temporary<-tweetdata$dictitems                #'temporary' contains all info except the state list
  temporary2<-c(temporary$created_at,temporary$id_str,temporary$text)
  temporary3<-as.matrix(temporary2)
  temp4<-t(temporary3)
  tempdata<-as.data.frame(temp4)
  colnames(tempdata)<-c("Datetime","ID","Text")
  df<-rbind(df,tempdata)
  colnames(df)<-c("Datetime","ID","Text") #resetting names
#   print(df)
}

#add the column with the hashtag
df$hashtag<-rep("gunrights",length(df$Text))

# Write CSV in R
write.csv(df, file = "data/gunrights_1402018_2208.csv",row.names=FALSE)

```

